name: 'WIPAC Dev Py Setup'
description: 'GitHub Action Package for Automating Python-Package Setup'

inputs:
  base-keywords:  # id of input
    description: 'A list of keywords to add to metadata'
    required: false
    default: ''
  directory-exclude:  # id of input
    description: 'A list of directories to exclude from release'
    required: false
    default: 'test tests doc docs resource resources example examples'
  license:  # id of input
    description: "The repo's license type"
    required: false
    default: 'MIT'
  git_committer_name:
    description: 'The name used for "git config user.name"'
    required: false
    default: github-actions
  git_committer_email:
    description: 'The email used for "git config user.email"'
    required: false
    default: github-actions@github.com

# outputs:
#   random-number:
#     description: "Random number"
#     value: ${{ steps.random-number-generator.outputs.random-id }}

runs:
  using: "composite"
  steps:
    - name: Dump GitHub Context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
      shell: bash

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # NOTE: update, someday. Also tests.yml

    - name: Is this the most recent commit? It won't be if the action was reran
      run: |
        git fetch &> /dev/null
        if [[ $(git status -sb | grep behind) ]]; then
          echo "IS_GIT_BEHIND=true" >> $GITHUB_ENV
          echo "this commit is not the most recent on this branch -- rest of action will be skipped"
        fi
      shell: bash

    - name: Git config
      if: env.IS_GIT_BEHIND != 'true'
      run: |
        git config user.name ${{ inputs.git_committer_name }}
        git config user.email ${{ inputs.git_committer_email }}
      shell: bash

    - name: Build setup.cfg + README.md (and commit)
      if: env.IS_GIT_BEHIND != 'true'
      run: |
        sudo apt-get update
        pip3 install -r ${{ github.action_path }}/requirements.txt
        pip3 install wipac-dev-tools

        echo $GITHUB_REPOSITORY
        echo "setup.cfg (+ README.md)"
        # since GHA injects raw string, must use EOF to avoid quote-mangling
        HEAD_COMMIT_MESSAGE=$(cat <<EOF
        ${{ github.event.head_commit.message }}
        EOF
        )
        # Build!
        python3 ${{ github.action_path }}/setup_builder.py \
          setup.cfg \
          $GITHUB_REPOSITORY \
          --base-keywords ${{ inputs.base-keywords }} \
          --directory-exclude ${{ inputs.directory-exclude }} \
          --license ${{ inputs.license }} \
          --token ${{ github.token }} \
          --commit-message "$HEAD_COMMIT_MESSAGE"
        cat setup.cfg
        # Commits
        git add setup.cfg
        git commit -m "<bot> update setup.cfg" || true
        git add README.md || true
        git commit -m "<bot> update README.md" || true
      shell: bash

    - name: Add py.typed file(s) (and commit)
      if: env.IS_GIT_BEHIND != 'true'
      run: |
        python -c '
        import os
        from pathlib import Path

        line_to_parse = ""
        with open("setup.cfg") as f:
          for line in f.readlines():
            if line.startswith("version_variable = "):
              line_to_parse = line.strip()  # remove newline
        if not line_to_parse:
          raise Exception("Cannot addd py.typed files (missing version_variable in setup.cfg)")

        for version_path in line_to_parse.removeprefix("version_variable = ").split(","):
          print(version_path)
          dpath = version_path.removesuffix("__init__.py:__version__")
          print(dpath)
          fpath = Path(dpath) / "py.typed"
          print(fpath)
          fpath.touch()  # create if needed!
        '
        git add .  # won't error if nothing to add
        git commit -m "<bot> add py.typed file(s)" || true

      shell: bash

    - name: Build dependencies.log (and commit)
      if: env.IS_GIT_BEHIND != 'true'
      run: |
        # append permissive line to .gitignore since *.log is commonly present
        line='!dependencies*.log'
        if [[ ! $(grep -F "$line" .gitignore) ]]; then
          echo "" >> .gitignore
          echo "" >> .gitignore
          echo "# wipac-dev-py-setup-action" >> .gitignore
          echo "$line" >> .gitignore
          git add .gitignore
          git commit -m "<bot> update .gitignore" || true  # okay if no change
          tail .gitignore
        fi

        # remove any old ones, then regenerate only what's needed
        rm dependencies*.log || true

        export PACKAGE_NAME=$(python3 ${{ github.action_path }}/get_package_name.py setup.cfg)

        # Build
        if [ -f ./Dockerfile ]; then
          # from docker...
          for f in ./Dockerfile*; do
              echo $f
              ${{ github.action_path }}/build-dependencies-dockerfile-logs.sh $f
          done
        else
          # from setup.cfg...
          export GITHUB_ACTION_PATH=${{ github.action_path }}
          ${{ github.action_path }}/build-dependencies-logs.sh
        fi

        # Commit
        git add .
        git commit -m "<bot> update dependencies*.log files(s)" || true  # okay if no change

      shell: bash

    - name: Push changes
      if: env.IS_GIT_BEHIND != 'true'
      run: |
        status=`git status 2>&1 | tee`
        ahead=`echo -n "${status}" 2> /dev/null | grep "Your branch is ahead of" &> /dev/null; echo "$?"`
        if [ "$ahead" -eq "1" ]; then
          echo "no changes needed"
          exit 0
        fi
        git push
        echo "changes pushed"
      shell: bash
