name: 'WIPAC Dev Py Setup'
description: 'GitHub Action Package for Automating Python-Package Setup'

inputs:
  # REQUIRED
  mode:
    description: |
      The mode to use:
        PACKAGING           - setup packaging files, metadata, etc. for the project 
        PACKAGING_AND_PYPI  - PACKAGING, plus additional metadata needed to publish to PyPI
    required: true  # needs to be explicitly checked
  python_min:
    description: 'Minimum required Python version'
    required: true  # needs to be explicitly checked
  # OPTIONAL (python)
  python_max:
    description: 'Maximum supported Python version. If not provided, the most recent Python version will be used.'
    required: false
    default: ''
  # OPTIONAL (packaging)
  package_dirs:
    description: "Space-separated list of directories to release. If not provided, all packages in the repository's root directory will be used."
    required: false
    default: ''
  exclude_dirs:
    description: "Space-separated list of directories to exclude from release, relative to the repository's root directory."
    required: false
    default: 'test tests doc docs resource resources example examples'
  # OPTIONAL (releases)
  pypi_name:
    description: 'Name of the PyPI package'
    required: false
    default: ''
  # OPTIONAL (meta)
  keywords_comma:
    description: 'Comma-delimited list of keywords (no quotes)'
    required: false
    default: ''
  author:
    description: 'Author of the package (required if the package is intended to be hosted on PyPI)'
    required: false
    default: ''
  author_email:
    description: 'Email of the package author (required if the package is intended to be hosted on PyPI)'
    required: false
    default: ''
  auto_mypy_option:
    description: 'Whether to auto create/update the `mypy` install option plus its dependencies'
    required: false
    default: 'True'
  # OPTIONAL (git)
  git_committer_name:
    description: 'Name used for "git config user.name"'
    required: false
    default: github-actions
  git_committer_email:
    description: 'Email used for "git config user.email"'
    required: false
    default: github-actions@github.com


runs:
  using: "composite"
  steps:
    - name: check required inputs
      run: |
        # step: check required inputs
        set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
        
        # required inputs 
        
        if [ -z "${{ inputs.mode }}" ]; then
          echo "::error::required input not provided: mode"
          exit 1
        fi
        if [ -z "${{ inputs.python_min }}" ]; then
          echo "::error::required input not provided: python_min"
          exit 1
        fi
        
        # deprecated inputs
        
        if [ -n "${{ inputs.keywords }}" ]; then
          echo "::error::'keywords' input is deprecated: use 'keywords_comma'"
          exit 1
        fi
        
        if [ -n "${{ inputs.patch_without_tag }}" ]; then
          echo "::error::'patch_without_tag' input is deprecated: use 'WIPACrepo/wipac-dev-next-version-action' ('force-patch-if-no-commit-token')"
          exit 1
        fi
      shell: bash

    - uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # NOTE: update, someday.

    - name: Is this most recent commit?
      run: |
        # step: Is this most recent commit?
        set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
        
        git fetch &> /dev/null
        if [[ $(git status -sb | grep behind) ]]; then
          echo "IS_GIT_BEHIND=true" >> $GITHUB_ENV
          echo "this commit is not most recent on this branch -- rest of action will be skipped"
        fi
      shell: bash

    - name: Git config
      if: env.IS_GIT_BEHIND != 'true'
      run: |
        # step: Git config
        set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
        git config user.name ${{ inputs.git_committer_name }}
        git config user.email ${{ inputs.git_committer_email }}
      shell: bash

    - name: Check pyproject.toml for project migration
      if: env.IS_GIT_BEHIND != 'true'
      run: |
        # step: Check pyproject.toml for project migration
        set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
        
        # if needed: auto-create a minimal pyproject.toml
        if [[ ! -f pyproject.toml ]]; then
            touch pyproject.toml
            # TODO: update logic when https://github.com/WIPACrepo/wipac-dev-py-setup-action/issues/62
            # add required fields
            echo "# WIPACrepo/wipac-dev-py-setup-action@v4+ Migration Helper:" >> pyproject.toml
            echo "" >> pyproject.toml
            # add most likely needed fields
            echo "[project]" >> pyproject.toml
            echo "dependencies = []  # leave empty if there are no dependencies" >> pyproject.toml
            echo "" >> pyproject.toml
            echo "# optional sections:" >> pyproject.toml
            echo "" >> pyproject.toml
            echo "# [project.optional-dependencies]" >> pyproject.toml
            echo "# foo = []" >> pyproject.toml
            echo "# bar = []" >> pyproject.toml
            # commit, push, exit
            msg="added pyproject.toml -- ALERT: user needs to set values for auto-added fields"
            git add .
            git commit -m "<bot> $msg"
            git push
            echo $msg
            echo "IS_GIT_BEHIND=true" >> $GITHUB_ENV
        fi
        # no setup.cfg allowed!
        if [[ -f setup.cfg ]]; then
            echo " "
            echo "WIPACrepo/wipac-dev-py-setup-action no longer supports 'setup.cfg'"
            echo "Migration Steps:"
            echo "  1. Look at 'pyproject.toml'--this action may have auto-added fields."
            echo "     Fill out any needed values."
            echo "  2. Manually move attributes from setup.cfg's [wipac:cicd_setup_builder]"
            echo "     section to WIPACrepo/wipac-dev-py-setup-action's 'with' block."
            echo "     See https://github.com/WIPACrepo/wipac-dev-py-setup-action#inputs."
            echo "  3. Migrate any non-autogenerated configuration to 'pyproject.toml'."
            echo "  4. Delete 'setup.cfg'."
            echo "  5. If used, update WIPACrepo/wipac-dev-py-versions-action to most"
            echo "     recent version."
            echo "     See https://github.com/WIPACrepo/wipac-dev-py-versions-action."
            echo "  6. Push these changes!"
            exit 1
        fi
      shell: bash

    - name: Detect MIT License or fallback only if missing
      if: env.IS_GIT_BEHIND != 'true'
      run: |
        # step: Detect MIT License or fallback only if missing
        set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"

        LICENSE_FILE="LICENSE"

        if [[ -f "$LICENSE_FILE" ]]; then
          if grep -iq "MIT License" "$LICENSE_FILE"; then
            echo "LICENSE_SPDX_ID=MIT" >> $GITHUB_ENV
            echo "LICENSE_FILE=$LICENSE_FILE" >> $GITHUB_ENV
          else
            echo "::error::LICENSE file found but does not contain 'MIT License'"
            exit 1
          fi
        else  # NO FILE 
          echo "::warning::LICENSE file not found — falling back to MIT"
          echo "LICENSE_SPDX_ID=MIT" >> $GITHUB_ENV
          echo "LICENSE_FILE=" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Build pyproject.toml + README.md (and commit)
      if: env.IS_GIT_BEHIND != 'true'
      run: |
        # step: Build pyproject.toml + README.md (and commit)
        set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
        
        set -e
        sudo apt-get update
        python -m venv action_venv
        . action_venv/bin/activate
        pip3 install -r ${{ github.action_path }}/requirements.txt

        # Build!
        set -x
        export PYPROJECT_KEYWORDS_JSON
        python3 ${{ github.action_path }}/pyproject_toml_builder.py \
          --toml pyproject.toml \
          --github-full-repo $GITHUB_REPOSITORY \
          --token ${{ github.token }} \
          --mode ${{ inputs.mode }} \
          --python-min "${{ inputs.python_min }}" \
          --python-max "${{ inputs.python_max }}" \
          --package-dirs ${{ inputs.package_dirs }} \
          --exclude-dirs ${{ inputs.exclude_dirs }} \
          --pypi-name "${{ inputs.pypi_name }}" \
          --keywords "${{ inputs.keywords_comma }}" \
          --author "${{ inputs.author }}" \
          --author-email "${{ inputs.author_email }}" \
          --license-spdx-id "$LICENSE_SPDX_ID" \
          --license-file "$LICENSE_FILE" \
          --auto-mypy-option "${{ inputs.auto_mypy_option }}"
        set +x
        
        # format (inc. sorting sections)
        pip install toml-sort
        toml-sort --in-place --ignore-case pyproject.toml
        
        cat pyproject.toml
        
        rm -rf action_venv
        
        # Commits
        git add pyproject.toml
        git commit -m "<bot> update pyproject.toml" || true
        git add README.md || true
        git commit -m "<bot> update README.md" || true
      shell: bash

    - name: Add py.typed file(s) (and commit)
      if: env.IS_GIT_BEHIND != 'true'
      run: |
        # step: Add py.typed file(s) (and commit)
        set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
        
        python -c '
        import os, sys
        from pathlib import Path
        
        sys.path.append(os.path.abspath("${{ github.action_path }}"))
        from find_packages import iterate_dirnames
        
        for pkg_dname in iterate_dirnames(Path("."), "${{ inputs.exclude_dirs }}".split()):
          print(pkg_dname)
          fpath = Path(pkg_dname) / "py.typed"
          print(fpath)
          fpath.touch()  # create if needed!
        '
        git add .  # won't error if nothing to add
        git commit -m "<bot> add py.typed file(s)" || true
      shell: bash

    - name: Push changes
      if: env.IS_GIT_BEHIND != 'true'
      run: |
        # step: Push changes
        set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
        
        status=`git status 2>&1 | tee`
        ahead=`echo -n "${status}" 2> /dev/null | grep "Your branch is ahead of" &> /dev/null; echo "$?"`
        if [ "$ahead" -eq "1" ]; then
          echo "no changes needed"
          exit 0
        fi
        git push
        echo "changes pushed"
      shell: bash
