name: tests

on: [ push ]

jobs:

  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: WIPACrepo/wipac-dev-flake8-action@v1.0

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - uses: WIPACrepo/wipac-dev-mypy-action@v1.2

  test:
    runs-on: ubuntu-latest
    env:
      PY_COLORS: "1"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt
      - run: pip install -r requirements-dev.txt
      - run: |
          pytest tests/test_setup_builder.py -vvv --maxfail=1